### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by tonyshkurenko** [de-vri-es/tokio-seqpacket-rs#1]
Hi, I'm novice in io rust libraries, I wonder how to use it with tokio (or any other) timeouts?

**Comment by de-vri-es** [comment]
There is no explicit support for timeouts in this crate, but you can wrap the created futures with [`tokio::time::timeout`](https://docs.rs/tokio/0.2.22/tokio/time/fn.timeout.html). It does add another layer of `Result` on top, so you end up with a `Result<Result<usize, std::io::Error>, tokio::time::Elapsed>`.

It would be relatively straightforward to add a timeout function that merges them back together and gives an `std::io::Error` with [`ErrorKind::TimedOut`](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.TimedOut`). However, that sounds like a function that makes more sense within `tokio` itself.

```rust
use tokio::time::timeout;
use std::time::Duration;

let result = timeout(Duration::from_secs(1), socket.send(b"Hello world!")).await;
```

**Comment by de-vri-es** [comment]
I'm assuming this answers your question, so I'll close the issue. Feel free to comment here if something is still unclear :)
