### ISSUE TITLE
Expose `writable()`

### ISSUE THREAD

**Issue by jyn514** [de-vri-es/tokio-seqpacket-rs#15]
Right now, `tokio-seqpacket` exposes `send()`, but not `writable()`. This causes issues for applications that want to do low-level sending using the file descriptor (e.g. with https://docs.rs/nix/latest/nix/sys/socket/fn.sendmsg.html) with APIs that aren't async. In particular, the only way to replicate `UdpSocket::writable` that I can think of is to busy loop, which defeats the point of an async API.

**Comment by jyn514** [comment]
Happy to work on this myself :) if I don't have it done today I should have it working tomorrow.

**Comment by de-vri-es** [comment]
Hey! I see your point. Correct use of `readable()` and `writable()` is a bit tricky, but that's no reason not to allow it.

But maybe we could just add `as_async_fd()` and return a `&tokio::AsyncFd`. Then whatever `tokio` decides to add to it later is automatically available.

**Comment by jyn514** [comment]
Oh wow, I didn't know about AsyncFd! That looks perfect, thanks so much :) I'll make a PR for that today.
